### ISSUE TITLE
combine with koa-qs

### ISSUE THREAD

**Issue by dead-horse** [koajs/querystring-strict#1]
this is easily ignored by users as I noticed, can we combine this with [koa-qs](https://github.com/koajs/qs) add a setting in `koa` like `express` did.

```
var app = koa();
app.queryParser = 'strict' // 'simple', 'extended'
```

any thoughts? @koajs/owners

**Comment by jonathanong** [comment]
i don't think it should be included in koa. we can do `qs(koa, 'strict')` or `'simple'` or `'extended'` or whatever options.

**Comment by fengmk2** [comment]
I try to send a pr for koa-qs.

**Comment by jonathanong** [comment]
added both of you to that repo. i only use the basic query string parser ;)

**Comment by fengmk2** [comment]
@jonathanong yep, we use basic too. And we also want `string` only by default inside our company's koa-inside.

Too avoid some stupid mistake.

**Comment by dead-horse** [comment]
my concern is lots of people didn't notice what `this.query` does, actually I only want to use the strict mode parser so `q=foo&q=bar` won't break my code. The more parser does, user's input is more uncontrollable.

or we can add a note in `koa`'s doc after we finished `koa-qs`.

**Comment by fengmk2** [comment]
Which's the default mode? `strict`?

**Comment by dead-horse** [comment]
`extended` for compatibility IMO

**Comment by fengmk2** [comment]
OK, will be done soon.

**Comment by fengmk2** [comment]
after https://github.com/koajs/qs/pull/3 this merge. I depd this module. haha!

**Comment by dougwilson** [comment]
Just if you guys were wondering, when I get around to adding strict to Express, it'll be the other way around: every value is going to be an array, rather than a string.

**Comment by dead-horse** [comment]
hmmm, array can retain all the inputs, but it make the code a little difficult to maintain. 

I've checked google, yahoo and github

- https://www.google.com/search?q=foo&q=bar : the real query is `foo bar`
- https://search.yahoo.com/search;_ylt=AvBIkxtX0fN2XNayfLRg9rebvZx4?p=foo&p=bar : the real query is 
- https://github.com/search?q=foo&q=bar : the real query is `bar`

**Comment by dougwilson** [comment]
They all so it differently, because their programmers didn't think about what they were doing before they did it :) I mean, the general "I want the first item case" would be `var search = req.query.q && req.query.q[0]`? When I get around to it, there is going to be an issue for the Express community to discuss, of course.

**Comment by fengmk2** [comment]
@dead-horse maybe `strict` meaning every value to array will be more meaningful.

@dougwilson @dead-horse And we can add two mode for string only: `first` and `last`.

- `first`: `var search = req.query.q && req.query.q[0]`
- `last`: `var search = req.query.q && req.query.q[req.query.q.length - 1]`
